apiVersion: batch/v1
kind: CronJob
metadata:
  name: zabbix-partitioner
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
            - env:
                - name: ZABBIX_REPOSITORY
                  value: >-
                    https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
                - name: LOG_PATH
                  value: /var/log/mysql_zbx_part.log
                - name: DB_HOST
                  value: 10.9.14.20
                - name: DB_PORT
                  value: '6033'
                - name: DB_DATABASE
                  value: zabbix
                - name: TZ
                  value: Etc/UTC
              envFrom:
                - secretRef:
                    name: zabbix-partitioner-mysql
                    optional: false
              image: cjohnson282/sc-zabbix-partition:latest
              imagePullPolicy: Always
              name: container-0
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 28 17 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
