apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-server-mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-server-mysql
      namespace: default
    spec:
      containers:
        - env:
            - name: ZBX_WEBSERVICEURL
              value: https://zabbix-web-service:10053/report
          envFrom:
            - configMapRef:
                name: zabbix-db-cfg
                optional: false
            - secretRef:
                name: mysqlrootpasswd
                optional: false
            - secretRef:
                name: zabbixmysql
                optional: false
          image: zabbix/zabbix-server-mysql
          imagePullPolicy: Always
          name: container-0
