apiVersion: v1
data:
  ZBX_SERVER_HOST: zabbix-server-mysql
kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ZBX_SERVER_HOST: {}
  name: zabbix-env-cfg
