apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-nginx-mysql
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
          envFrom:
            - configMapRef:
                name: zabbix-db-cfg
                optional: false
            - configMapRef:
                name: zabbix-env-cfg
                optional: false
            - secretRef:
                name: zabbixmysql
                optional: false
          image: zabbix/zabbix-web-nginx-mysql
          imagePullPolicy: Always
          name: container-0
