apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-nginx-mysql
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
          image: zabbix/zabbix-web-nginx-mysql
          imagePullPolicy: Always
          name: container-0
