apiVersion: v1
data:
  DB_SERVER_HOST: 10.9.14.20
  DB_SERVER_PORT: '6033'
kind: ConfigMap
metadata:
  creationTimestamp: '2024-07-02T22:35:03Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:DB_SERVER_HOST: {}
          f:DB_SERVER_PORT: {}
      manager: agent
      operation: Update
      time: '2024-07-02T22:35:03Z'
  name: zabbix-db-cfg
  namespace: default
  resourceVersion: '59001'
  uid: a673c058-937f-4062-9dd4-6b4883692517
