apiVersion: batch/v1
kind: CronJob
metadata:
  managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:metadata:
              f:namespace: {}
            f:spec:
              f:template:
                f:spec:
                  f:affinity: {}
                  f:containers:
                    k:{"name":"container-0"}:
                      .: {}
                      f:env:
                        .: {}
                        k:{"name":"DB_DATABASE"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"DB_HOST"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"DB_PORT"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"LOG_PATH"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"TZ"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"ZABBIX_REPOSITORY"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:terminationGracePeriodSeconds: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
      manager: agent
      operation: Update
  name: zabbix-partitioner
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      namespace: default
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
            - env:
                - name: ZABBIX_REPOSITORY
                  value: >-
                    https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
                - name: LOG_PATH
                  value: /var/log/mysql_zbx_part.log
                - name: DB_HOST
                  value: 10.9.14.20
                - name: DB_PORT
                  value: '6033'
                - name: DB_DATABASE
                  value: zabbix
                - name: TZ
                  value: ETC/UTC
              envFrom:
                - secretRef:
                    name: zabbix-partitioner-mysql
                    optional: false
              image: cjohnson282/sc-zabbix-partition:latest
              imagePullPolicy: Always
              name: container-0
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 28 17 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
