apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2024-07-02T20:51:42Z'
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-web-nginx-mysql
  name: zabbix-web-nginx-mysql
  namespace: default
  resourceVersion: '24171'
  uid: 58dd15bb-7ee8-44da-b146-e82e4b8a15f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-web-nginx-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-web-nginx-mysql
      namespace: default
    spec:
      affinity: {}
      containers:
        - envFrom:
            - secretRef:
                name: zabbixmysql
                optional: false
            - configMapRef:
                name: zabbix-env-cfg
                optional: false
            - configMapRef:
                name: zabbix-db-cfg
                optional: false
          image: zabbix/zabbix-web-nginx-mysql
          imagePullPolicy: Always
          name: container-0
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
