apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-mysql-service
  labels:
    app: guestbook
    tier: frontend
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/zabbix-server-mysql"]'
    management.cattle.io/ui-managed: 'true'
spec:
  type: NodePort
  ports:
  - port: 10051
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-web-nginx-mysql
