apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-zabbix-agent
  ports:
    - name: myport
      port: 10050
      protocol: TCP
      targetPort: 10050
  type: ClusterIP
