apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
spec:
  dnsNames:
    - monitoring.sentracam.net
  secretName: monitoring-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
